---
- name: Build Boxfuse image and push to Dockerhub
  hosts: builder
  become: yes

tasks:
    - name: Ensure docker is present
      apt:
        name: docker.io
        state: present

    - name: Ensure git is present
      apt:
        name: git
        state: present        

    - name: Clone boxfuse multistage dockerfile from git
      git:
        repo: 'https://github.com/ufndtwocmeu/BoxfuseMultistageDocker.git'
        dest: /data

    - name: Build image and push it to Dockerhub
      docker_image:
        build:
          path: /data/BoxfuseMultistageDocker
        name: ufndtwocmeu/myboxfuse:1.0
        push: yes
        source: build
      

- name: Run container from Boxfuse image
  hosts: prod
  become: yes

tasks:
    - name: Ensure docker is present
      apt:
        name: docker.io
        state: present

    - name: Run Boxfuse container
      docker_container:
        name: boxfuseprod
        image: ufndtwocmeu/myboxfuse:1.0
        published_ports: 8888:8080