---
- name: Build Boxfuse image and push to Dockerhub
  hosts: builder
  become: yes

  vars_prompt:
    - name: dockerhubrepo
      prompt: "Enter your docker hub repository name to push image to:"
      private: no

  tasks:
    - name: Ensure docker is present
      apt:
        name: docker.io
        state: present

    - name: Copy docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: Chmode docker-compose
      shell: chmod +x /usr/local/bin/docker-compose

    - name: Ensure git is present
      apt:
        name: git
        state: present        

    - name: Clone boxfuse multistage dockerfile from git
      git:
        repo: https://github.com/ufndtwocmeu/BoxfuseMultistageDocker.git
        dest: /data/BoxfuseMultistageDocker

    - name: Build image and push it to Dockerhub
      docker_image:
        build:
          path: /data/BoxfuseMultistageDocker
        name: "{{dockerhubrepo}}/myboxfuse:1.0"
        source: build
        push: yes

- name: Run container from Boxfuse image
  hosts: prod
  become: yes

  tasks:
    - name: Ensure docker is present
      apt:
        name: docker.io
        state: present

    - name: Run Boxfuse container
      docker_container:
        name: boxfuseprod
        image: "{{dockerhubrepo}}/myboxfuse:1.0"
        published_ports: 8888:8080